[package]
name = "rfrp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
quinn = { version = "0.11", features = ["rustls", "ring"] }
rustls = { version = "0.23", features = ["std"] }
rustls-pemfile = "2"
rcgen = "0.13"
anyhow = "1.0"